# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Build Package'
description: 'Common steps for building and pushing Docker images'

inputs:
  package_name:
    required: true
    description: 'Name of the package to build'
  tags:
    required: true
    description: 'Docker tags to apply (can be multiline YAML string)'
  registry:
    required: false
    default: 'ghcr.io'
    description: 'Container registry domain'
  image_name:
    required: false
    description: 'Base image name (repository name)'
  build_args:
    required: false
    default: ''
    description: 'Build arguments from preprocess script'
  generate_attestation:
    required: false
    default: 'false'
    description: 'Whether to generate artifact attestation'
  save_image_info:
    required: false
    default: 'false'
    description: 'Whether to save image tags to an artifact (for PR builds)'
  skyhook_agent_image:
    required: false
    default: 'ghcr.io/nvidia/skyhook/agent:latest'
    description: 'Skyhook agent container image to use for validation'

outputs:
  image_tags:
    description: 'The tags that were applied to the built image'
    value: ${{ steps.meta.outputs.tags }}
  image_digest:
    description: 'The digest of the built image'
    value: ${{ steps.push.outputs.digest }}

runs:
  using: 'composite'
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate package version map
      id: package-versions
      shell: bash
      run: |
        # Get all tags, extract package/version pairs, find latest for each package
        PACKAGE_VERSIONS=$(git tag -l | \
          grep -E '^[^/]+/[0-9]+\.[0-9]+\.[0-9]+$' | \
          sort -t/ -k1,1 -k2,2V | \
          awk -F/ '
            {
              package = $1
              version = $2
              packages[package] = version
            }
            END {
              printf "{"
              first = 1
              for (package in packages) {
                if (!first) printf ","
                printf "\"%s\":\"%s\"", package, packages[package]
                first = 0
              }
              printf "}"
            }
          ')
        
        echo "PACKAGE_VERSIONS=${PACKAGE_VERSIONS}" >> $GITHUB_OUTPUT
        echo "Generated package version map: ${PACKAGE_VERSIONS}"

    - name: Run preprocess script
      id: preprocess
      shell: bash
      env:
        PACKAGE_VERSIONS: ${{ steps.package-versions.outputs.PACKAGE_VERSIONS }}
      run: |
        echo "PACKAGE_VERSIONS from previous step: ${PACKAGE_VERSIONS}"
        PREPROCESS_SCRIPT="${{ inputs.package_name }}/preprocess.sh"
        if [ -f "$PREPROCESS_SCRIPT" ]; then
          echo "Running preprocess script: $PREPROCESS_SCRIPT"
          chmod +x "$PREPROCESS_SCRIPT"
          "$PREPROCESS_SCRIPT"
        else
          echo "No preprocess script found at $PREPROCESS_SCRIPT"
          echo "BUILD_ARGS=" >> $GITHUB_OUTPUT
        fi

    - name: Check if config.json exists and changed
      id: check-config
      shell: bash
      run: |
        CONFIG_FILE="${{ inputs.package_name }}/config.json"
        DOCKERFILE="${{ inputs.package_name }}/Dockerfile"
        
        if [ ! -f "$CONFIG_FILE" ]; then
          # Check if Dockerfile exists and has a FROM that references a skyhook-packages image
          if [ -f "$DOCKERFILE" ]; then
            # Check if FROM line contains "skyhook-packages" (indicating it inherits from another package)
            if grep -q "^FROM.*skyhook-packages" "$DOCKERFILE"; then
              echo "config_exists=false" >> $GITHUB_OUTPUT
              echo "config_changed=false" >> $GITHUB_OUTPUT
              echo "No config.json found, but Dockerfile inherits from skyhook-packages image - validation skipped"
              exit 0
            fi
          fi
          
          # If we get here, config.json is missing and it's not inheriting from skyhook-packages
          echo "ERROR: config.json is required for package ${{ inputs.package_name }}" >&2
          echo "Package must have a config.json file unless it inherits from another skyhook-packages image." >&2
          if [ -f "$DOCKERFILE" ]; then
            echo "Current Dockerfile FROM line:" >&2
            grep "^FROM" "$DOCKERFILE" >&2 || echo "  (no FROM line found)" >&2
          fi
          exit 1
        fi
        
        echo "config_exists=true" >> $GITHUB_OUTPUT
        
        # For PR builds, check if config.json was changed
        # For tag builds (push events), always validate
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          # Check if config.json was changed in this PR
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q "^${CONFIG_FILE}$"; then
            echo "config_changed=true" >> $GITHUB_OUTPUT
            echo "config.json was changed in this PR, validation required"
          else
            echo "config_changed=false" >> $GITHUB_OUTPUT
            echo "config.json was not changed in this PR, skipping validation"
          fi
        else
          # For tag builds or other push events, always validate
          echo "config_changed=true" >> $GITHUB_OUTPUT
          echo "Tag build detected, validating config.json"
        fi

    - name: Check if package inherits from skyhook-packages
      id: check-inheritance
      if: steps.check-config.outputs.config_exists == 'true' && steps.check-config.outputs.config_changed == 'true'
      shell: bash
      run: |
        DOCKERFILE="${{ inputs.package_name }}/Dockerfile"
        
        if [ -f "$DOCKERFILE" ] && grep -q "^FROM.*skyhook-packages" "$DOCKERFILE"; then
          echo "inherits_from_skyhook_packages=true" >> $GITHUB_OUTPUT
          echo "Package inherits from skyhook-packages image - will use validate-inherited target"
        else
          echo "inherits_from_skyhook_packages=false" >> $GITHUB_OUTPUT
          echo "Package is standalone - will use validate-standalone target"
        fi

    - name: Validate config.json (standalone packages)
      if: steps.check-config.outputs.config_exists == 'true' && steps.check-config.outputs.config_changed == 'true' && steps.check-inheritance.outputs.inherits_from_skyhook_packages == 'false'
      shell: bash
      run: |
        make validate-standalone PACKAGE="${{ inputs.package_name }}"

    - name: Validate config.json (inherited packages)
      if: steps.check-config.outputs.config_exists == 'true' && steps.check-config.outputs.config_changed == 'true' && steps.check-inheritance.outputs.inherits_from_skyhook_packages == 'true'
      shell: bash
      run: |
        make validate-inherited PACKAGE="${{ inputs.package_name }}"

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}/${{ inputs.package_name }}
        tags: ${{ inputs.tags }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.package_name }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        build-args: ${{ steps.preprocess.outputs.BUILD_ARGS != '' && steps.preprocess.outputs.BUILD_ARGS || inputs.build_args }}

    - name: Generate artifact attestation
      if: inputs.generate_attestation == 'true'
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ inputs.registry }}/${{ inputs.image_name }}/${{ inputs.package_name }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    - name: Save image info
      if: inputs.save_image_info == 'true'
      shell: bash
      run: |
        mkdir -p /tmp/image-info
        echo "${{ steps.meta.outputs.tags }}" > /tmp/image-info/${{ inputs.package_name }}.txt

    - name: Upload image info
      if: inputs.save_image_info == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: image-info-${{ inputs.package_name }}
        path: /tmp/image-info/${{ inputs.package_name }}.txt
        retention-days: 1
