#!/bin/bash

# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# AWS-specific bootloader configuration script
# This script creates a grub configuration file that will source /etc/tuned/bootcmdline
# when grub is configured. This ensures the settings are picked up on reboot regardless
# of when this script runs relative to tuned writing the bootcmdline file.

set -e

BOOTCMDLINE_FILE="/etc/tuned/bootcmdline"
GRUB_D_DIR="/etc/default/grub.d"
GRUB_CONFIG_FILE="${GRUB_D_DIR}/99_tuned.cfg"

# Ensure grub.d directory exists
mkdir -p "$GRUB_D_DIR"

# Write the grub configuration file
# This file will be sourced by the grub configuration system when update-grub runs
# It dynamically reads from /etc/tuned/bootcmdline at that time and sets GRUB_CMDLINE_LINUX_DEFAULT
cat <<EOF > "$GRUB_CONFIG_FILE"
# This file is auto-generated by AWS tuned profile bootloader script
# It sources bootloader settings from /etc/tuned/bootcmdline when grub is configured

# Source the tuned bootcmdline
if [ -f "$BOOTCMDLINE_FILE" ]; then
    . $BOOTCMDLINE_FILE
    GRUB_CMDLINE_LINUX_DEFAULT=" \${TUNED_BOOT_CMDLINE}"
fi
EOF

chmod a+x "$GRUB_CONFIG_FILE"
update-grub

echo "Created grub configuration: $GRUB_CONFIG_FILE"
echo "This file will source $BOOTCMDLINE_FILE when grub is configured"